version: '2'

services:
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - REDIS_PASSWORD=password
    ports:
      - '6379:6379'
    volumes:
      - ./keywords_api/redis_data:/bitnami/redis/data
  
  keywords_api:
    build: ./keywords_api
    ports:
      - '4000:4000'
    depends_on:
      - redis

  keywords_update_synonyms:
    build: ./keywords_update
    command: python -u synonyms.py
    depends_on:
      - keywords_api
    
  keywords_update_tags:
    build: ./keywords_update
    depends_on:
      - keywords_api