version: '2.2'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - ./neo4j_data_loader/neo4j_data:/data
  
  visualizer:
    build: ./visualizer
    ports:
      - '4000:4000'
    depends_on:
      - neo4j