version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "job_urls:2:1,job_descriptions:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./kafka-logs:/kafka
  
  job_description_scraper1:
    build: ./job_scraper
    depends_on:
      - kafka

  job_description_scraper2:
    build: ./job_scraper
    depends_on:
      - kafka
     
  job_url_scraper:
    build: ./job_scraper
    depends_on:
      - kafka
    command: python -u job_url_scraper.py
   