version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "job_urls:2:1,job_descriptions:2:1,job_keywords:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./kafka-logs:/kafka
  
  job_description_scraper1:
    build: ./job_scraper
    depends_on:
      - kafka

  job_description_scraper2:
    build: ./job_scraper
    depends_on:
      - kafka
     
  job_url_scraper:
    build: ./job_scraper
    depends_on:
      - kafka
    command: python -u job_url_scraper.py

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - REDIS_PASSWORD=password
    ports:
      - '6379:6379'
    volumes:
      - ./keywords_api/redis_data:/bitnami/redis/data
  
  keywords_api:
    build: ./keywords_api
    ports:
      - '4000:4000'
    depends_on:
      - redis

  job_keywords_parser1:
    build: ./job_keywords_parser
    depends_on:
      - kafka
      - keywords_api
  
  job_keywords_parser2:
    build: ./job_keywords_parser
    depends_on:
      - kafka
      - keywords_api

  #keywords_update_synonyms:
  #  build: ./keywords_update
  #  command: python -u synonyms.py
  #  depends_on:
  #    - keywords_api
    
  #keywords_update_tags:
  #  build: ./keywords_update
  #  depends_on:
  #    - keywords_api
   