version: '2.2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
        
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "job_urls:2:1,job_descriptions:2:1,job_keywords:2:1,job_search:1:1,errors:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./kafka_logs:/logs
        
  kafka_ui:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication"
    depends_on:
      - kafka
      - zookeeper
    
  job_description_scraper:
    build: ./job_description_scraper
    depends_on:
      - kafka
    scale: 2
     
  job_url_scraper:
    build: ./job_url_scraper
    depends_on:
      - kafka

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - REDIS_PASSWORD=password
    ports:
      - '6379:6379'
    volumes:
      - ./keywords_api/redis_data:/bitnami/redis/data
  
  keywords_api:
    build: ./keywords_api
    ports:
      - '4000:4000'
    depends_on:
      - redis

  job_keywords_parser:
    build: ./job_keywords_parser
    depends_on:
      - kafka
      - keywords_api
    scale: 2

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - ./neo4j_data_loader/neo4j_data:/data
        
  neo4j_data_loader:
    build: ./neo4j_data_loader
    depends_on:
      - neo4j
      - kafka
    scale: 2

  visualizer:
    build: ./visualizer
    ports:
      - '5000:5000'
    depends_on:
      - neo4j
      - kafka
