KAFKA = 'kafka:9092'
KAFKA_CONSUMER_GROUP = 'parsers'
KAFKA_INPUT_TOPIC = 'job_descriptions'
KAFKA_OUTPUT_TOPIC = 'job_keywords'
KAFKA_ERROR_TOPIC = 'errors'
KEYWORDS_API = 'http://keywords_api:4000/keywords/'
